version: "3"
services:
  users:
    image: users
    container_name: users
    restart: always
    ports:
      - 3003:80
    env_file:
      - ./Users/.env
    depends_on:
      - users-db
    networks:
      - bigbank-network

  accounts:
    image: accounts
    container_name: accounts
    restart: always
    ports:
      - 3001:80
    env_file:
      - ./Accounts/.env
    depends_on:
      - accounts-db
    networks:
      - bigbank-network

  transfers:
    image: transfers
    container_name: transfers
    restart: always
    ports:
      - 3002:80
    env_file:
      - ./Transfers/.env
    depends_on:
      - transfers-db
    networks:
      - bigbank-network

  notification:
    image: notification
    container_name: notification
    restart: always
    ports:
      - 3004:80
    networks:
      - bigbank-network

  users-db:
    image: mongo
    container_name: users-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/users:/data/db
    networks:
      - bigbank-network

  accounts-db:
    image: mongo
    container_name: accounts-db
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/accounts:/data/db
    networks:
      - bigbank-network

  transfers-db:
    image: mongo
    container_name: transfers-db
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/transfers:/data/db
    networks:
      - bigbank-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: users-db,accounts-db,transfers-db
    depends_on:
      - users-db
    networks:
      - bigbank-network

networks:
  bigbank-network:
