services:
  users-db:
    image: mongo:7.0
    container_name: users-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - users-data-db:/data/db
    networks:
      - telemetry

  tickets-db:
    build:
      context: ../Tickets/.
      dockerfile: ../Tickets/Dockerfile-mongodb
    container_name: tickets-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27018
    command: --replSet rs0 --keyFile /etc/mongo-keyfile --bind_ip_all --port 27018
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'tickets-db:27018'}]}) }" | mongosh --port 27018 -u root -p example --authenticationDatabase admin > /dev/null
      interval: 5s
      timeout: 15s
      start_period: 15s
      retries: 10
    volumes:
      - tickets-data-db:/data/db
    networks:
      - telemetry

  events-db:
    image: mongo:7.0
    container_name: events-db
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - events-data-db:/data/db
    networks:
      - telemetry

  auth-db:
    image: mongo:7.0
    container_name: auth-db
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - auth-data-db:/data/db
    networks:
      - telemetry


  users1:
    image: users
    build:
      context: ../Users/.
    container_name: users1
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - ../Users/.env
    depends_on:
      - users-db
      - rabbitmq
    networks:
      - telemetry

  users2:
    image: users
    build:
      context: ../Users/.
    container_name: users2
    restart: always
    ports:
      - "4002:3002"
    env_file:
      - ../Users/.env
    depends_on:
      - users-db
      - rabbitmq
    networks:
      - telemetry

  tickets1:
    image: tickets
    build:
      context: ../Tickets/.
    container_name: tickets1
    restart: always
    ports:
      - "3004:3004"
    env_file:
      - ../Tickets/.env
    depends_on:
      - tickets-db
      - rabbitmq
    networks:
      - telemetry

  tickets2:
    image: tickets
    build:
      context: ../Tickets/.
    container_name: tickets2
    restart: always
    ports:
      - "4004:3004"
    env_file:
      - ../Tickets/.env
    depends_on:
      - tickets-db
      - rabbitmq
    networks:
      - telemetry

  events1:
    image: events
    build:
      context: ../Events/.
    container_name: events1
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ../Events/.env
    depends_on:
      - events-db
      - rabbitmq
    networks:
      - telemetry

  events2:
    image: events
    build:
      context: ../Events/.
    container_name: events2
    restart: always
    ports:
      - "4001:3001"
    env_file:
      - ../Events/.env
    depends_on:
      - events-db
      - rabbitmq
    networks:
      - telemetry

  auth1:
    image: auth
    build:
      context: ../Auth/.
    container_name: auth1
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - ../Auth/.env
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - telemetry

  auth2:
    image: auth
    build:
      context: ../Auth/.
    container_name: auth2
    restart: always
    ports:
      - "4003:3003"
    env_file:
      - ../Auth/.env
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - telemetry


  nginx-gateway:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - users1
      - users2
      - tickets1
      - tickets2
      - events1
      - events2
      - auth1
      - auth2
      - notification
    networks:
      - telemetry

  notification:
    image: notification
    build:
      context: ../Notification/.
    container_name: notification
    restart: always
    ports:
      - "3005:3005"
    env_file:
      - ../Notification/.env
    depends_on:
      - rabbitmq
    networks:
      - telemetry

  rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq
    ports:
      - 5672:5672    #amqp
      - 15672:15672  #http
      - 15692:15692  #prometheus
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
    networks:
      - telemetry

  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    volumes:
      - ./otel/otel-collector-config-connector.yml:/etc/otelcol/otel-collector-config.yml
    command: --config /etc/otelcol/otel-collector-config.yml
    depends_on:
      - jaeger
    ports:
      - "4317:4317" # Port gRPC
      - "55681:55681" # Port HTTP
    networks:
      - telemetry

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
    networks:
      - telemetry


  swagger:
    image: swagger
    container_name: swagger
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - users1
      - users2
      # - tickets
      # - events
      # - auth
    networks:
      - telemetry

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    devices:
      - /dev/kmsg:/dev/kmsg
    depends_on:
      - users1
      - users2
      - users-db
    networks:
      - telemetry

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus:/etc/prometheusification
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - telemetry

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: always
    user: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - telemetry

  mongodb_exporter:
    image: percona/mongodb_exporter:0.40.0
    container_name: mongodb_exporter
    restart: always
    command: --mongodb.uri="mongodb://root:example@users-db:27017/UsersDB?authSource=admin&authMechanism=SCRAM-SHA-256" --collect-all --discovering-mode
    ports:
      - "9216:9216"
    depends_on:
      - users-db
    networks:
      - telemetry

networks:
  telemetry:

volumes:
  users-data-db: {}
  events-data-db: {}
  tickets-data-db: {}
  auth-data-db: {}