global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "users1"
    static_configs:
      - targets: ["users1:3002"]

  - job_name: "users2"
    static_configs:
      - targets: ["users2:4002"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "mongodb_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090","mongodb_exporter:9216"]

  - job_name: aggregated-trace-metrics
    static_configs:
    - targets: ['otel_collector:8889']
